###
GET http://localhost:8080/users

###
GET http://localhost:8080/users/2

###

GET http://localhost:8080/rooms

###

GET http://localhost:8080/rooms/3

###

POST http://localhost:8080/users
Content-Type: application/json

{
  "id": 0,
  "name": "Bars",
  "room": {
    "id": 2
  }
}


###

GET http://localhost:8080/users/check?userId=6&roomId=3

###

GET http://localhost:8080/users/check?userId=6&roomId=3


###

GET project-license-number.herokuapp.com/numbers/generateRandom